changelog:
  exclude:
    labels:
      - "skip-changelog"
  categories:
    - title: "Breaking Changes"
      labels:
        - "breaking"
        - "major"
    - title: "Features"
      labels:
        - "feature"
        - "enhancement"
    - title: "Bug Fixes"
      labels:
        - "bug"
        - "fix"
    - title: "Documentation"
      labels:
        - "docs"
        - "documentation"
    - title: "Chores"
      labels:
        - "chore"
        - "maintenance"
    - title: "Other"
      labels:
        - "*"
